services:
  frontend:
    build: ./frontend
    ports:
      - "80:8000"
  backend:
    build: ./backend
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: db
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
    ports:
      - "8080:8080"
  mysql:
    image: mysql:9.1
    restart: always
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
